import os
import django
import json

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mysite.settings')
django.setup()

from portfolio.models import About

def seed():
    print("Seeding About section data...")
    
    # We want exactly one About object.
    about, created = About.objects.get_or_create(id=1)
    
    # Existing personal fields (leave alone if already set, or default them)
    if not about.name: about.name = "Ahelan"
    if not about.email: about.email = "ahelanv2006@gmail.com"
    if not about.phone: about.phone = "+91 7200673492"
    if not about.bio: about.bio = "I build digital products end to end..."
    
    # New Frontend fields (English)
    about.heading_1 = "Design is how I think —"
    about.heading_2 = "business is how I"
    about.heading_em = "aim"
    about.heading_3 = "it."
    about.education_text = "MSc International Business · Montpellier Business School · 2024–2026 · Global Market Intelligence · Strategic Leadership · AI in Business"
    
    # New Frontend fields (French)
    about.fr_heading_1 = "Le design, c’est ma façon de penser —"
    about.fr_heading_2 = "le business, ma façon de la"
    about.fr_heading_em = "diriger"
    about.fr_heading_3 = "."
    about.fr_education_text = "MSc International Business · Montpellier Business School · 2024–2026 · Intelligence des marchés · Leadership stratégique · IA en entreprise"
    
    # Marquee JSON
    about.marquee_1 = [
        "Product Design",
        "UX Design",
        "UI Design",
        "Design Systems",
        "User Research",
        "Interaction Design",
        "Design Thinking",
    ]
    about.marquee_2 = [
        "Wireframing",
        "Prototyping",
        "Visual Design",
        "Accessibility",
        "Motion Design",
        "Figma",
        "Framer",
        "AI-Assisted Design",
        "Frontend Development",
    ]
    
    # Metrics JSON
    about.metrics = [
        { "value": "1st", "count": None, "label": "Sophia Antipolis Innovation Hackathon — LockAI", "fr_label": "Hackathon Innovation Sophia Antipolis — LockAI" },
        { "value": "3+", "count": 3, "suffix": "+", "label": "Years of cross-functional product experience", "fr_label": "Ans d’expérience produit transversale" },
        { "value": "$70K+", "count": 70, "prefix": "$", "suffix": "K+", "label": "Revenue generated by conversion-focused work", "fr_label": "Revenus générés par un travail orienté conversion" },
        { "value": "1B+", "count": None, "label": "Tonnes of CO₂ the product I design aims to avoid by 2050", "fr_label": "Tonnes de CO₂ que le produit que je conçois vise à éviter d’ici 2050" }
    ]
    
    about.save()
    print("Done seeding About data!")

if __name__ == "__main__":
    seed()
