# Generated by Django 5.2.11 on 2026-08-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Internship', 'Internship'), ('Full-time', 'Full-time'), ('Hackathon', 'Hackathon'), ('Freelance', 'Freelance')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('achievements', models.JSONField(default=list, help_text='List of achievements (strings)')),
                ('outcome', models.CharField(max_length=300)),
                ('skills', models.JSONField(default=list, help_text='List of skills (strings)')),
                ('color', models.CharField(help_text='Hex color code (e.g. #0072E3)', max_length=20)),
                ('fg', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='portfolio/companies/')),
                ('logo_variant', models.CharField(blank=True, choices=[('tile', 'Tile'), ('plate', 'Plate')], max_length=20, null=True)),
                ('logo_aspect', models.FloatField(blank=True, help_text='Aspect ratio (width / height)', null=True)),
                ('logo_placement', models.CharField(blank=True, choices=[('right', 'Right'), ('below', 'Below')], max_length=20, null=True)),
                ('fr_role', models.CharField(blank=True, max_length=200, null=True)),
                ('fr_summary', models.TextField(blank=True, null=True)),
                ('fr_outcome', models.CharField(blank=True, max_length=300, null=True)),
                ('fr_achievements', models.JSONField(blank=True, default=list, help_text='French list of achievements (strings)')),
                ('order', models.IntegerField(default=0, help_text='Order in which to display (lower is earlier)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
