# Generated by Django 5.2.11 on 2026-08-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(help_text='e.g. 2.1', max_length=20)),
                ('issuer', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=300)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=200, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('skills', models.JSONField(default=list, help_text='List of skills (strings)')),
                ('metric_value', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_label', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='portfolio/issuers/')),
                ('logo_aspect', models.FloatField(blank=True, help_text='Aspect ratio (width / height)', null=True)),
                ('fr_title', models.CharField(blank=True, max_length=300, null=True)),
                ('fr_skills', models.JSONField(blank=True, default=list, help_text='French list of skills (strings)')),
                ('fr_metric_label', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which to display (lower is earlier)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
