# Generated by Django 5.2.11 on 2026-08-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='education_text',
            field=models.CharField(blank=True, help_text='e.g. MSc International Business...', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='fr_education_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='fr_heading_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='fr_heading_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='fr_heading_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='fr_heading_em',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='heading_1',
            field=models.CharField(blank=True, help_text='e.g. Design is how I think —', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='heading_2',
            field=models.CharField(blank=True, help_text='e.g. business is how I', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='heading_3',
            field=models.CharField(blank=True, help_text='e.g. it.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='heading_em',
            field=models.CharField(blank=True, help_text='e.g. aim', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='marquee_1',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for top marquee'),
        ),
        migrations.AddField(
            model_name='about',
            name='marquee_2',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for bottom marquee'),
        ),
        migrations.AddField(
            model_name='about',
            name='metrics',
            field=models.JSONField(blank=True, default=list, help_text='List of metric objects'),
        ),
    ]
