# Generated by Django 5.2.11 on 2026-08-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_about_education_text_about_fr_education_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cta_text',
            field=models.CharField(blank=True, help_text='e.g. Explore My Work', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='fr_cta_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
