# Generated by Django 5.2.11 on 2026-08-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_about_cta_text_about_fr_cta_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('story', models.TextField()),
                ('bridge', models.TextField()),
                ('fr_title', models.CharField(blank=True, max_length=200, null=True)),
                ('fr_place', models.CharField(blank=True, max_length=200, null=True)),
                ('fr_story', models.TextField(blank=True, null=True)),
                ('fr_bridge', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which to display (lower is earlier)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
